---
version: "3.9"
services:

  # base build python images
  python:
    image: gcr.io/cryptoline/python
    env_file:
      - .env
    build:
      context: .
      dockerfile: containers/python/python.dockerfile
    networks:
      crypto:
  
  # run command inside the container
  mirror:
    image: gcr.io/cryptoline/python
    env_file:
      - .env
    volumes:
      - ./:/cryptoline/:z
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      SQLALCHEMY_DATABASE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
    networks:
      crypto:

    depends_on:
      - postgres

  postgres:
    image: postgres:13.3-alpine
    volumes:
      - ./db/conf/postgresql.conf:/etc/postgresql.conf
      - ./db/extension.sql:/docker-entrypoint-initdb.d/psql-extension.sql
    command: postgres -c config_file=/etc/postgresql.conf
    environment:
      PGDATA: /data
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432  
    networks:
      crypto:

networks:
  crypto: